---
  - name: Get switch info
    hosts: switches
    
    vars: 
      ansible_network_os: ios
      ansible_connection: network_cli
      ansible_command_timeout: 90
      ping: false

    tasks:
    - name: Gather info
      ansible.builtin.ping:
      when:  ping