---
  - name: Get switch info
    hosts: switches
    
    vars: 
      ansible_network_os: ios
      ansible_connection_network: network_cli
      ansible_command_timeout: 90

    tasks:
    - name: Gather info
      ansible.builtin.ping:
