---
# Ansible Playbook to upgrade Cisco IOS 

# Play 1: Check current version
- name: Check current CISCO IOS version
  hosts: switches
  vars: 
    upgrade_ios_version: 1.1.1

  tasks:
    - name: CHECK CURRENT VERSION
      when: run_play_1
      ios_facts:

    - debug: 
        msg: 
        - "Current version is {{ ansible_net_version }}"
        - "Upgrade image is {{ upgrade_ios_version }}"

    - debug: 
        msg: 
        - "Image is not compliant and will be upgraded"
      when: ansible_net_version != upgrade_ios_version


# Play 2: Create backup folder
- name: Create backup folder
  hosts: localhost
  connection: local
   

  tasks:
   - name: Get ansible date/time facts
     when: run_play_2
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store DTG as fact
     when: run_play_2
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars.localhost.DTG}}
     when: run_play_2
     file:
      path: ~/network-programmability/backups/{{hostvars.localhost.DTG}}
      state: directory
  run_once: true

# Play 3: Backup existing config
- name: Backup existing config
  hosts: switches 

  tasks:
   - name: Backup Running Config
     when: run_play_3  
     ios_command:
       commands: show run  
     register: config

   - name: Save output to ~/backups/
     when: run_play_3
     copy:
       content: "{{config.stdout[0]}}"
       dest: "~/backups/{{hostvars.localhost.DTG}}/{{ inventory_hostname }}-{{hostvars.localhost.DTG}}-config.txt"

   - name: Save running config 
     when: run_play_3
     ios_config:
       save_when: always 

# Play 4: Copy image
- name: Copy Image to switch
  hosts: switches

  tasks:
   - name: Copy Image // This could take a while...
     when: run_play_4
     net_put:
       src: "/var/images/cat9k_iosxe.16.06.06.SPA.bin"
       dest: "flash:/cat9k_iosxe.16.06.06.SPA-02.bin"
     vars:
       ansible_command_timeout: 3600
       ansible_network_cli_ssh_type: paramiko

# Play 5: Change the Boot Variable to the new image 
- name: Change Boot image
  hosts: switches
  
  tasks:
   - name: Change Boot Variable to new image 
     when: run_play_5
     ios_config: 
       commands: 
         - "boot system flash:cat9k_iosxe.16.06.06.SPA-02.bin"
       save_when: always 

   ## Reload the device 
   - name: Reload the Device
     when: run_play_5 
     cli_command: 
       command: reload
       prompt: 
         - confirm
       answer: 
         - 'y'
         
   # Wait for Reachability to the device 
   - name: Wait for device to come back online
     when: run_play_5
     wait_for:
       host: "{{ inventory_hostname }}"
       port: 22
       delay: 90
     delegate_to: localhost

   # Check current image 
   - name: Check Image Version      
     when: run_play_5
     ios_facts:

   - debug: 
       msg: 
       - "Current version is {{ ansible_net_version }}"

   
   - name: ASSERT THAT THE IOS VERSION IS CORRECT
     when: run_play_5
     assert:
       that:
         - upgrade_ios_version == ansible_net_version
   - debug: 
       msg: 
       - "Software Upgrade has been completed"
