---
# Ansible Playbook to upgrade Cisco IOS 

- name: Check CISCO IOS version
  hosts: switches

  vars: 
    upgrade_ios_version: 1.1.1

  tasks:
    - name: CHECK CURRENT VERSION
      ios_facts:

    - debug: 
        msg: 
        - "Current version is {{ ansible_net_version }}"
        - "Upgrade image is {{ upgrade_ios_version }}"

    - debug: 
        msg: 
        - "Image is not compliant and will be upgraded"

      when: ansible_net_version != upgrade_ios_version


- name: Create backup folder
  hosts: localhost
  connection: local

  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars.localhost.DTG}}
     file:
      path: ~/network-programmability/backups/{{hostvars.localhost.DTG}}
      state: directory
  run_once: true

- name: Backup existing config
  hosts: switches 

  tasks:
   - name: Backup Running Config  
     ios_command:
       commands: show run  
     register: config

   - name: Save output to ~/network-programmability/backups/
     copy:
       content: "{{config.stdout[0]}}"
       dest: "~/network-programmability/backups/{{hostvars.localhost.DTG}}/{{ inventory_hostname }}-{{hostvars.localhost.DTG}}-config.txt"

## SAVE the Running Config 

   - name: Save running config 
     ios_config:
       save_when: always 

## copy image
   - name: Copy Image // This could take up to 4 minutes
     net_put:
       src: "/var/images/cat9k_iosxe.16.06.06.SPA.bin"
       dest: "flash:/cat9k_iosxe.16.06.06.SPA-02.bin"
     vars:
       ansible_command_timeout: 1800
       ansible_network_cli_ssh_type: paramiko

## Change the Boot Variable to the new image 

   - name: Change Boot Variable to new image 
     ios_config: 
       commands: 
         - "boot system flash:cat9k_iosxe.16.06.06.SPA-02.bin"
       save_when: always 

## Reload the device 

   - name: Reload the Device 
     cli_command: 
       command: reload
       prompt: 
         - confirm
       answer: 
         - 'y'
         
## Wait for Reachability to the device 

   - name: Wait for device to come back online
     wait_for:
       host: "{{ inventory_hostname }}"
       port: 22
       delay: 90
     delegate_to: localhost

## Check current image 

   - name: Check Image Version      
     ios_facts:

   - debug: 
       msg: 
       - "Current version is {{ ansible_net_version }}"

   - name: ASSERT THAT THE IOS VERSION IS CORRECT


     assert:
       that:
         - upgrade_ios_version == ansible_net_version
   - debug: 
       msg: 
       - "Software Upgrade has been completed"
